version: '3'

services:
  jenkins:
    image: 'jenkins/jenkins:2.150.1'
    container_name: jenkins
    restart: always
    ports:
      - '8080:8080'
      - '50000:50000'
    volumes:
      - /vagrant/jenkins_home:/var/jenkins_home
